5:5 ****ERROR**** ignoring unterminated string literal
6:2 ****ERROR**** ignoring unterminated string literal
7:4 ****ERROR**** ignoring string literal with bad escaped character
8:5 ****ERROR**** ignoring unterminated string literal with bad escaped character
9:1 ****ERROR**** ignoring unterminated string literal with bad escaped character
11:1 ****WARNING**** integer literal too large; using max value
12:1 ****WARNING**** integer literal too large; using max value
15:1 ****ERROR**** ignoring illegal character: @
15:2 ****ERROR**** ignoring illegal character: #
15:3 ****ERROR**** ignoring illegal character: $
15:4 ****ERROR**** ignoring illegal character: :
